version: '3.8'

services:
  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    ports:
      - "3000:3000" # Gitea web UI
      - "222:22"   # SSH
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro 
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea.db
      - GITEA__server__ROOT_URL=http://localhost:3000/
    restart: always

  gitea-runner:
    image: gitea/act_runner:latest
    container_name: gitea-runner
    depends_on:
      - gitea
    environment:
      - GITEA_INSTANCE_URL=http://gitea:3000
      - RUNNER_TOKEN=YOUR_RUNNER_TOKEN
      - RUNNER_NAME=gitea-runner
      - RUNNER_CAPACITY=10
    restart: always

  netbootxyz:
    image: linuxserver/netbootxyz:latest
    container_name: netbootxyz
    ports:
      - "3001:3000" # Netboot.xyz web UI
      - "69:69/udp" # TFTP server
      - "4011:4011/udp" # PXE boot
    volumes:
      - netbootxyz-data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    restart: always

volumes:
  gitea-data:
  netbootxyz-data: